#!/usr/bin/env bash
if [ -z "$DISPLAY" ]; then
    emacsclient -nw -a "" "$@"
else
    emacsclient -n -e "(> (length (frame-list)) 1)" | grep t
    if [ "$?" = "1" ]; then
        emacsclient -c -n -a "" "$@"
    else
        emacsclient -n -a "" "$@"
    fi
fi
