[buildPlans.iosevka-custom]     # Plan name
family = "Iosevka"              # Font menu family name
design = [                      # Common Styles
  "type",                       # Some symbols become full-width
  "ss08",                       # Based on PragmataPro
  "v-zero-slashed"              # Slashed 0
]

[buildPlans.iosevka-custom-mono] # Plan name
family = "Iosevka Mono"          # Font menu family name
design = [                       # Common Styles
  "term",                        # Only monospaced symbols
  "ss08",                        # Based on PragmataPro
  "v-zero-slashed"               # Slashed 0
]
