[buildPlans.iosevka-custom] # Plan name
family = "Iosevka"          # Font menu family name

# Common styles to upright, italic, and oblique
design = [
  "term",                   # Monospaced symbols without ligatures
  "ss08",                   # Based on PragmataPro
]
